// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9mk0JlE6-SkmnvKsqgXv8wpnYg_6MjWI',
    appId: '1:718360790950:web:904023f37003f7024eb167',
    messagingSenderId: '718360790950',
    projectId: 'caravan-app-38626',
    authDomain: 'caravan-app-38626.firebaseapp.com',
    storageBucket: 'caravan-app-38626.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8AWANCrZxGh6nMC3xvYeSokrEjuFfgw',
    appId: '1:718360790950:android:846266e4f664c91b4eb167',
    messagingSenderId: '718360790950',
    projectId: 'caravan-app-38626',
    storageBucket: 'caravan-app-38626.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrQ_qXVanqJANPtBfErDAaNYa-Ng46nB8',
    appId: '1:718360790950:ios:f764b90766ca74b44eb167',
    messagingSenderId: '718360790950',
    projectId: 'caravan-app-38626',
    storageBucket: 'caravan-app-38626.firebasestorage.app',
    iosBundleId: 'com.example.caravanAppSimple',
  );

}